[[headers]]
  for = "/*.geojson"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
